// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Teste_Grupo_SKA_Vitor_Nicacio.DAO;

#nullable disable

namespace Teste_Grupo_SKA_Vitor_Nicacio.Migrations
{
    [DbContext(typeof(DataBaseContext))]
    [Migration("20231104015602_[SKAVitor]")]
    partial class SKAVitor
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Teste_Grupo_SKA_Vitor_Nicacio.Models.BlocoNotas", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<DateTime>("DATA_INCLUSAO")
                        .HasColumnType("datetime2");

                    b.Property<string>("NOTA")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("STATUS")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("tabelaBlocoNotas");
                });
#pragma warning restore 612, 618
        }
    }
}
